---
apiVersion: xl-deploy/v1
kind: Applications
spec:
  - name: BacktraceApp
    type: udm.Application
    children:
      - name: Applications/BacktraceApp/1.0.0
        type: udm.DeploymentPackage
        deployables:
        - name: docker-backtrace-app-web
          type: docker.ContainerSpec
          containerName: backtrace-app
          image: vlussenburg/backtrace-app-web:1.0.0
          environment:
            BACKTRACE_ENDPOINT: "{{BACKTRACE_ENDPOINT}}"
            BACKTRACE_TOKEN: "{{BACKTRACE_TOKEN}}"
            APPLICATION_VERSION: "1.0.0"
            APPLICATION_NAME: "backtrace-app"
          showLogsAfter: "5"
          portBindings:
          - name: pm-8080
            type: docker.PortSpec
            hostPort: "8080"
            containerPort: "5000"
---

apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/host
  type: overthere.LocalHost
  os: UNIX
- name: docker
  type: docker.Engine
  dockerHost: !value DOCKER_HOST
---

apiVersion: xl-deploy/v1
kind: Environments
spec:
  - name: backtrace-app-dict
    type: udm.Dictionary
    entries:
      BACKTRACE_ENDPOINT: !value BACKTRACE_ENDPOINT
      BACKTRACE_TOKEN: !value BACKTRACE_TOKEN
  - name: Environments/dev
    type: udm.Environment
    members:
    - ~Infrastructure/docker
    dictionaries:
    - Environments/backtrace-app-dict