apiVersion: xl-release/v1
kind: Templates
spec:
- name: Jenkins
  type: jenkins.Server
  # to prevent circular reference in docker network, use 'external address'
  url:  http://ip-172-31-42-192.ec2.internal:80
  username: !value jenkins_username
  password: !value jenkins_password
- name: XL Deploy
  type: xldeploy.XLDeployServer
  url: http://xld:4516
  username: !value xld_username
  password: !value xld_password
- name: Xebialabs JIRA
  type: jira.Server
  url: !value jira_url
  username: !value jira_username
  password: !value jira_password
- name: snow
  type: servicenow.Server
  url: !value snow_url
  username: !value snow_username
  password: !value snow_password
  useServicenowApp: "True"
- name: backtraceio
  type: backtraceio.Server
  url: https://testing-xebialabs.sp.backtrace.io
  username: !value backtrace_username
  password: !value backtrace_password
  universe: testing-xebialabs